spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food-delivery-bot-db?prepareThreshold=0
    username: postgres
    password: password
  liquibase:
    enabled: true

kafka:
  get-courier-location:
    servers: localhost:9092
    login: kafka
    password: password
    topic: "courier-location"
  send-courier-location:
    servers: localhost:9092
    login: kafka
    password: password
    topic: "courier-location"

